apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: _APP_NAME_
  name: _APP_NAME_
  namespace: microservices
spec:
  replicas: _REPL_NUMBER_
  selector:
    matchLabels:
      app: _APP_NAME_
  template:
    metadata:
      labels:
        app: _APP_NAME_
    spec:
      containers:
        - image: _IMAGE_NAME_
          name: _APP_NAME_
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cfm-_APP_NAME_
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "128Mi"
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: registry-credentials
      restartPolicy: Always
