apiVersion: v1
kind: Service
metadata:
  name: srv-_APP_NAME_
  namespace: microservices
  labels:
    app: srv-_APP_NAME_
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: _APP_NAME_
